import blurMap from "./blur-map.json";

const map = blurMap as Record<string, string>;

/**
 * Build-time LQIP (blur-up placeholder) for a public image path, e.g. "/images/hero.png".
 * Generated by `npm run blur` (scripts/generate-blur-map.mjs). Server-side only — importing
 * this pulls the full blur map, so don't use it in client components; for client-graph
 * images, compute the value on the server and pass it down as a prop.
 */
export function getBlur(src?: string): string | undefined {
  return src ? map[src] : undefined;
}
